### ISSUE TITLE
synchronization issues with dictionary objects in a class

### ISSUE THREAD

**Issue by qpxu007** [redis-collections/redis-collections#134]
Test code (testx.py):

```python
from redis_collections import *

from redis import Redis
from pprint import pprint

test_d = {'2': {'id': 2,
                'name': 'Pause',
                'isChecked': True,
                'parameter1': None,
                'parameter2': None},
          'current': 0,
          '4': {'id': 4,
                'name': 'Collect',
                'isChecked': True,
                'parameter1': '0',
                'parameter2': '1'}}


r = Redis()

d = Dict(key='test')
if not dict(d):
    d.update(test_d)


class Test():
    def __init__(self):
        self.D = Dict(key='test', writeback=True)

    def getd(self):
        print('current=', self.D.get('current'))
        #pprint(self.D)
        return self.D.get('current')

    def update(self, hash):
        self.D.update(hash)
        self.D.sync()
        print("after adding:", self.D)


Tx = Test()

```
# Test procedure (two concurrent sessions A & B):

## A: 

from testx import Tx

## B: 

from testx import Tx

## A: 

Tx.getd()

===> 0

## B:

Tx.getd()

====> 0

#A:

Tx.update({'current':2})
Tx.getd()

====> 2

#B:

Tx.getd()

===> 0

how do I force a fetch from redis instead of the cached version? Thanks.

**Comment by qpxu007** [comment]
I was able to make it work with a cache reset on B: Tx.D.cache ={}, or create a new dict, are these the correct way?

**Comment by bbayles** [comment]
Does it work with `writeback=False`? See [the docs](https://redis-collections.readthedocs.io/en/stable/usage-notes.html#synchronization). This is what's causing it to use a local cache.

**Comment by qpxu007** [comment]
Indeed, the issue does not occur with writeback being off. The documentation seems to imply that there are problems using writeback being false. How to avoid the surprising behavior mentioned in the documentation?

Thanks

**Comment by bbayles** [comment]
I'm afraid there is no way around it: you either have a local cache that isn't automatically flushed to Redis, or you can't properly deal with mutable objects.

The sync function will send everything in the cache to Redis, for whatever that is worth.

**Comment by qpxu007** [comment]
So to clarify:

with writeback false (no cache used), local (single instance) consistency may not be guaranteed. However, if a sync is called after each write, will this problem be fixed for sure? --- this mode will work for concurrent processes.

with writeback true, local consistency is always guaranteed (with better performance I suppose). To use in a separate concurrent processes,   the same key'ed obj has to disable cache on reading to sync with redis.

Thanks.

**Comment by bbayles** [comment]
With `writeback=False` you can't really work with `list` and `dict` values - see the doc example.

```python
>>> D = Dict({'key': [1, 2]})  # Store a mutable object
>>> D['key'].append(3)  # Retrieve and modify the object
>>> D['key']  # Retrieve the object from Redis again
[1, 2]
```

With `writeback=True` you can, but you have to call `.sync` to send changes to Redis so other instances can see them.

**Comment by qpxu007** [comment]
Thanks for the clarifications. 

For writeback=False, does it work if the with context is used? it appears to based on the docs.

**Comment by bbayles** [comment]
The `with Dict(...)` form will automatically call `.sync` at the end of the block.

**Comment by qpxu007** [comment]
I am confused:

A:

D = Dict({'key': [1, 2]}, writeback=False)
D['key'].append(3)
  
D.sync() 

results: [1,2] after sync()


B: 
with D:
    D['key'].append(4)

results; [1,2,4]  

how come the difference is more than a sync() call?

**Comment by bbayles** [comment]
Your first example is just showing the problem with using mutable data and `writeback=False`. See an [identical example](https://docs.python.org/3/library/shelve.html#example) in Python's builtin `shelve` module.

Your second example shows how `writeback=True` fixes the issue. If you look inside Redis after your second example executes, you'll see `1, 2, 4` stored under your key.

---

What I think you're trying to do is this:

```python
>>> from redis_collections import Dict
>>> D = Dict({'key': [1, 2]}, key='my-key', writeback=True)
>>> E = Dict(key='my-key')
>>> D['key'].append(3)
>>> D.sync()
>>> E['key']
[1, 2, 3]
```

**Comment by qpxu007** [comment]
but in the second case, D was defined as writeback=False (i.e. identical to the first example)
