### ISSUE TITLE
`SyncableDict.sync()` *may* be not atomic

### ISSUE THREAD

**Issue by j178** [redis-collections/redis-collections#144]
Hi,

I find that the `.sync()` method of `SyncableDict` and its `SyncableX` brothers *may* be not atomic,
`.sync()` first deletes the key and then updates Redis from itself, these two operations can cause race condition,

I encountered this in production, but I am not sure is it a real problem, or by design.

**Comment by bbayles** [comment]
Thanks for the report. I'll have to look into this.

**Comment by bbayles** [comment]
OK, reading back through, my thought process for `SyncableDict` was:
* The [sync operation](https://github.com/redis-collections/redis-collections/blob/d04aba8c66068d58e2a21810d3a32a002038a8f1/redis_collections/syncable.py#L73-L74) does `clear` and then `update`.
* `clear` deletes the whole key, i.e. the hash table itself.
* `update` re-creates it with the local dictionary's contents.
* It's possible that some other process could manipulate the same key in between the `clear` and `delete`, but that's possible for every Redis operation - somebody else can delete your key and create something with a new data type there.
* The library tries to prevent collisions by creating a [random key](https://github.com/redis-collections/redis-collections/blob/d04aba8c66068d58e2a21810d3a32a002038a8f1/redis_collections/base.py#L82) by default.

How did your issue in production manifest? You had multiple processes using the same `SyncableDict`?

**Comment by j178** [comment]
Yes, I have multiple gunicorn worker operating on the same `SyncableDict`, like this:
```py
key = f"person:{id}"
person = SyncableDict(redis=redis, key=key)  # this line can be an empty dict
# ... doing something modification to `person`
person.sync()
```

At some point, some workers can get an empty dict at line 2 and then results in an error.

My thought was that is it possible to wrap both `clear` and `update` into a transaction?

**Comment by bbayles** [comment]
I think I've solved this in https://github.com/redis-collections/redis-collections/pull/145, but there's a tradeoff: there will temporarily be more data stored in Redis. It's possible to do the clear and re-populate operations in a transaction, but it would require some re-engineering of each collection to make that work.

Would you like to try this out?

**Comment by j178** [comment]
`rename` seems like a great idea, I'll try that!
