### ISSUE TITLE
only sync the local cache for LRUDict

### ISSUE THREAD

**Issue by beckermr** [redis-collections/redis-collections#151]
I think this line should maybe only sync the local cache:

https://github.com/redis-collections/redis-collections/blob/master/redis_collections/syncable.py#L292

**Comment by bbayles** [comment]
Thanks for the report. Could you explain what behavior is different from what you expect?

**Comment by beckermr** [comment]
Right so any key not in the cache should already be persisted onto disk. I'd expect only self.cache to need persisting, not self (which is a combination of the persisted keys and the cached ones).
